In [ ]:
print("Welcome to Numpy-2")

Welcome to Numpy-2


In [ ]:
import numpy as np

In [ ]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[3]

4

In [ ]:
a[-7]

4

In [ ]:
a[::2]

array([1, 3, 5, 7, 9])

In [ ]:
a[[1,4,6]] # we can pass list of indexes we want to index from 1D array

array([2, 5, 7])

In [ ]:
# a[(1,4,6)]

In [ ]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
a[::-2]

array([10,  8,  6,  4,  2])

In [ ]:
a[5:1:-1]

array([6, 5, 4, 3])

In [ ]:
a[-5:-9:-1]

array([6, 5, 4, 3])

In [ ]:
a[[1,4,6]]

array([2, 5, 7])

In [ ]:
b=np.arange(1,13).reshape((3,4))
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b[:2,:2]

array([[1, 2],
       [5, 6]])

In [ ]:
b[:,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [ ]:
b[::2,::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
b[[0,0,1,2],[0,2,3,1]] # we need to pass lists of row indices and column indices separately as list.

array([ 1,  3,  8, 10])

In [ ]:
b[(0,1),::2]

array([[1, 3],
       [5, 7]])

In [ ]:
b[::2,[0,1]]

array([[ 1,  2],
       [ 9, 10]])

In [ ]:
b[(0,1,2),1:2]

array([[ 2],
       [ 6],
       [10]])

In [ ]:
b[:,::-1]

In [ ]:
b[1,1]

6

In [ ]:
b[[0,1,2,2],[1,1,1,2]]

array([ 2,  6, 10, 11])

In [ ]:
c=np.arange(1,25).reshape(4,6)
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
c[(0,1,3),:]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
c[::2,::-2]

array([[ 6,  4,  2],
       [18, 16, 14]])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

1 (8,)


In [ ]:
m1 = np.array([[0,1,2,3],
[4,5,6,7],
[8,9,10,11]]).
What'll be the output of m1[0, 1:3]

In [ ]:
d=np.arange(12).reshape((3,4))
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
d[0, 1:3]

array([1, 2])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

1 (8,)


In [ ]:
b = np.array([1,2,3,4,5,6,7,8]).reshape((1,8))
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
b.shape

(3, 4)

In [ ]:
b.ndim

2

In [ ]:
a = np.array([0,1,2,3,4,5])
a[4:]=10


In [ ]:
a

array([ 0,  1,  2,  3, 10, 10])

In [ ]:
a+2

array([ 2,  3,  4,  5, 12, 12])

In [ ]:
a[2:4]=99

In [ ]:
a

array([ 0,  1, 99, 99, 10, 10])

In [ ]:
# Fancy Indexing


## Fancy indexing (Masking)

- Numpy arrays can be indexed with boolean arrays (masks). 
- This method is called fancy indexing. 

In [ ]:
e=np.arange(12).reshape((3,4))
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
mask=e<6
print(mask)

[[ True  True  True  True]
 [ True  True False False]
 [False False False False]]


- Same thing as algebric operations


- All the **values before 6 return `True`** and **all values after 6 return `False`**


- **Comparison operation also happens on each element**


- A **matrix having boolean values** `True` and `False` is returned 


- Based on the given **condition**

- **We can use this boolean matrix to filter our array**


#### Now, Let's use this to filter or mask values from our array

- **Condition will be passed instead of indices and slice ranges**

In [ ]:
e[mask]

array([0, 1, 2, 3, 4, 5])

In [ ]:
e[e<6]


array([0, 1, 2, 3, 4, 5])

In [ ]:
e[e%2==0]

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
e%2==0

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [ ]:
mask=(e%5==0)

In [ ]:
e[mask]

array([ 0,  5, 10])

In [ ]:
e[e%2==0].reshape((2,3))

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [ ]:
e[e%1==0].reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
e[]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
e[e%3==0]

array([0, 3, 6, 9])

#### But did you notice that matrix gets converted into a 1D array after masking?

#### It happens because

- To retain matrix shape, it **has to retain all the elements**
- It **cannot retain its original number of elements with lesser number of elements**
- So, this filtering operation **implicitly converts high-dimensional array into 1D array**


#### If we want, we can reshape the resulting 1D array into 2D

- But, we need to know **beforehand** what is the **dimension or number of elements** in resulting 1D array


# Multiple conditions in numpy

In [ ]:
mask=((e%2==0)&(e%3==0))

In [ ]:
e[mask]

array([0, 6])

In [ ]:
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
e%2==0

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [ ]:
e%3==0

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [ ]:
e[((e%2==0)&(e%3==0))]

array([0, 6])

In [ ]:
e[((e%2==0)|(e%3==0))]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
e[(e%2==0)|(e%3==0)]

array([ 0,  2,  3,  4,  6,  8,  9, 10])

In [ ]:
a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0)
a[mask] = -1
a

array([-1,  1, -1,  3, -1,  5])

In [ ]:
a = np.array([0,1,2,3,4,5])

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
mask = (a%2 == 0)
a[mask]

array([0, 2, 4])

In [ ]:
a

array([-1,  1, -1,  3, -1,  5])

In [ ]:
a=np.arange(11,16)
b=np.arange(1,6)
a+b

array([12, 14, 16, 18, 20])

In [ ]:
c=np.arange(11,16)
d=np.arange(1,7)
print(c)
print(d)

[11 12 13 14 15]
[1 2 3 4 5 6]


In [ ]:
c+d

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [ ]:
a*b

array([11, 24, 39, 56, 75])

In [ ]:
a-b

array([10, 10, 10, 10, 10])

In [ ]:
a/b

array([11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ])

In [ ]:
a**b

array([    11,    144,   2197,  38416, 759375])

## Aggregate / Universal Functions on 1D array (`ufunc`) 

#### What exactly is a `ufunc`?

#### Let's first start by understanding that

- **Ufuncs is short for Universal Functions**


- Ufuncs or universal functions operate on ndarrays in an **element-by-element fashion**. 


- A ufunc is like a **“vectorized” wrapper** for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs. 


#### What's so special about these ufuncs?

- Well, "ufunc" is just a term that we gave to **MATHEMATICAL FUNCTIONS in the Numpy library**. 


- Numpy provides various universal functions that cover a wide variety of operations.


- These functions **operate on ndarray (N-dimensional array) i.e Numpy’s array class.**


- They perform **fast element-wise array operations**.

#### Numpy universal functions are objects that belongs to `numpy.ufunc` class.

- Some ufuncs are **called automatically when the corresponding "arithmetic operator" is used on arrays**.


- That's how they are related to operations on numpy arrays


#### For example:
- When **addition of constant to array** is performed **element-wise** using `+` operator, then **np.add() is called internally.**

In [ ]:
a+b

array([12, 14, 16, 18, 20])

In [ ]:
np.add(a,b)

array([12, 14, 16, 18, 20])

In [ ]:
arr=np.arange(1,31).reshape((6,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
np.sum(arr)

465

In [ ]:
np.sum(arr,axis=0)

array([ 81,  87,  93,  99, 105])

In [ ]:
np.sum(arr,axis=1)

array([ 15,  40,  65,  90, 115, 140])

115

array([21, 22, 23, 24, 25])

115

In [ ]:
arr

#### Now, we want to find the minimum value in the array

**`np.min()` function can help us with this**

In [1]:
np.min(arr)

NameError: ignored

In [ ]:
np.min(arr,axis=0) 

array([1, 2, 3, 4, 5])

In [ ]:
np.max(arr,axis=1) # Finding max in horizontal direction

array([ 5, 10, 15, 20, 25, 30])

In [ ]:
np.zeros(3) # creates a matrix filled with all zeros

array([0., 0., 0.])

In [ ]:
a=np.zeros((3,4)) #creates a 2d matrix filled with all zeros

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(4)#creates a 1d array filled with all zeros

array([1., 1., 1., 1.])

In [ ]:
np.ones((4,5))#creates a 2d matrix filled with all ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
a+1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((3,4))*2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [ ]:
np.full((3,4),4.0) #creates a 2d matrix filled with all 4.0s

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
np.full((3,4),4)#creates a 2d matrix filled with all 4s

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

link for reference : https://numpy.org/doc/stable/user/basics.types.html

In [ ]:
np.ones((3,4),dtype=np.int32) # we can specify the dtype 


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [ ]:
np.identity(4) # creates an identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(4)# creates an identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(10,5)# creates an identity matrix with specified number of rows and columns

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.identity(4)*2

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [ ]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
np.diag([10,23,39]) # creates an  matrix diag matrix filled with values we provide

array([[10,  0,  0],
       [ 0, 23,  0],
       [ 0,  0, 39]])

In [ ]:
np.arange(1,14)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
# np.diag?

In [ ]:
np.diag(np.arange(1,14))

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13]])

#### Now, What if we want to check whether "any" element of array follows a specific condition?

#### Let's say we have 2 arrays:

#### Let's say we want to find out if any of the elements in array `m` is smaller than any of the corresponding elements in array `n`


In [ ]:
m=np.array([1,2,3,4])
n=np.array([0,1,2,3])
m<n # comparing element wise 2 numpy arrays

array([False, False, False, False])

In [ ]:
m=np.array([1,1,1,4])
n=np.array([0,1,2,3])
m==n

array([False,  True, False, False])

In [ ]:
m=np.array([4,3,2,6])
n=np.array([4,2,3,4])
m<n

array([False, False,  True, False])

#### `np.any()` 

- `any()` returns `True` if **any of the corresponding elements** in the argument arrays follow the **provided condition**.
- np.any() returns False only when there is NO non-zero element present in the array, i.e., when all array elements are zero


In [ ]:
np.any(m<n) 

True

In [ ]:
b=np.array([1,2,3,4])
d=np.array([0,1,2,3])
print(b<d)
np.any(b<d)

[False False False False]


False

#### Now, What if we want to check whether "all" the elements in our array follow a specific condition?

#### Again, Let's say we have 2 arrays:
#### Let's say we want to find out if all the elements in array `b` are smaller than all the corresponding elements in array `d`



In [ ]:
np.all(b<d)

False

In [ ]:
b=np.array([1,2,2,4])
d=np.array([0,1,2,3])
print(b>d)


[ True  True False  True]


In [ ]:
np.all(b>d)

False

In [ ]:
np.any(b>d)

True

In [ ]:
a=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

b=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

a==b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
print(np.all(a==b))

True


In [ ]:
a=np.array([[1, 2, 3],
 [4, 6, 6],
 [7, 8, 9]])

b=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

a>b

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [ ]:
print(np.any(a>b))

True


In [ ]:
a = np.array([0,2,3]) 
b = np.array([1,3,5])  
# What'll be the output of a >= b?

In [ ]:
a>=b

array([False, False, False])

In [ ]:
a= np.array([3,65,76,65,23,543,54,67,8,5,2,4])
a

array([  3,  65,  76,  65,  23, 543,  54,  67,   8,   5,   2,   4])

In [ ]:
mask=a<65

In [ ]:
mask

array([ True, False, False, False,  True, False,  True, False,  True,
        True,  True,  True])

In [ ]:
mask[3]

False

In [ ]:
f=np.arange(1,13).reshape((3,4))
f

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
f[f<5]

SyntaxError: invalid syntax (604391878.py, line 1)

In [ ]:
a=np.array([1,2,4,324,234])
a[2]=56
a

array([  1,   2,  56, 324, 234])

In [ ]:
b=a

In [ ]:
b

array([  1,   2,  56, 324, 234])

In [ ]:
b[2]=45

In [ ]:
b

array([  1,   2,  45, 324, 234])

In [ ]:
a

array([  1,   2,  45, 324, 234])

In [ ]:
b = np.array([[[1,2,3], [4,5,6]]]) 

In [ ]:
b

array([[[1, 2, 3],
        [4, 5, 6]]])