In [ ]:
print("Welcome to Numpy-3")

Welcome to Numpy-3


In [ ]:
import numpy as np


In [ ]:
!gdown 1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF

Downloading...
From: https://drive.google.com/uc?id=1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF
To: /Users/nikhilsanghi/Downloads/dsml-course-main-live/batches/May-Beg-Aug-Adv/fitness.txt
100%|██████████████████████████████████████| 3.14k/3.14k [00:00<00:00, 2.84MB/s]


In [ ]:
a=np.array([4,2,65,56,0,6,9])
a

array([ 4,  2, 65, 56,  0,  6,  9])

In [ ]:
np.sort(a)

array([ 0,  2,  4,  6,  9, 56, 65])

In [ ]:
a

array([ 4,  2, 65, 56,  0,  6,  9])

In [ ]:
a.sort()

In [ ]:
a

array([ 0,  2,  4,  6,  9, 56, 65])

In [ ]:
a

array([ 0,  2,  4,  6,  9, 56, 65])

In [ ]:
a

array([ 4,  2, 65, 56,  0,  6,  9])

In [ ]:
np.argsort(a)

array([4, 1, 0, 5, 6, 3, 2])

In [ ]:
np.max(a)

65

In [ ]:
np.argmax(a)

2

In [ ]:
np.argmin(a)

4

In [ ]:
np.min(a)

0

In [ ]:
a=np.array([4,2,56,0,6,9,56])
a

array([ 4,  2, 56,  0,  6,  9, 56])

In [ ]:

np.max(a)

56

In [ ]:
np.argmax(a)

2

In [ ]:
b=np.array([[23,2,54],[17,3,42],[15,5,65]])
b

array([[23,  2, 54],
       [17,  3, 42],
       [15,  5, 65]])

In [ ]:
np.sort(b)

array([[ 2, 23, 54],
       [ 3, 17, 42],
       [ 5, 15, 65]])

In [ ]:
np.sort(b,axis=0)

array([[15,  2, 42],
       [17,  3, 54],
       [23,  5, 65]])

In [ ]:
np.sort(b,axis=1)

array([[ 2, 23, 54],
       [ 3, 17, 42],
       [ 5, 15, 65]])

In [ ]:
b

array([[23,  2, 54],
       [17,  3, 42],
       [15,  5, 65]])

In [ ]:
np.sort(b,axis=0)

array([[15,  2, 42],
       [17,  3, 54],
       [23,  5, 65]])

In [ ]:
np.argsort(b,axis=0)

array([[2, 0, 1],
       [1, 1, 0],
       [0, 2, 2]])

In [ ]:
b

array([[23,  2, 54],
       [17,  3, 42],
       [15,  5, 65]])

In [ ]:
np.sort(b,axis=1)

array([[ 2, 23, 54],
       [ 3, 17, 42],
       [ 5, 15, 65]])

In [ ]:
np.argsort(b,axis=1)

array([[1, 0, 2],
       [1, 0, 2],
       [1, 0, 2]])

In [ ]:
data=np.loadtxt("/Users/nikhilsanghi/Downloads/dsml-course-main-live/batches/May-Beg-Aug-Adv/fitness.txt",dtype="str")

In [ ]:
data[:44]

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66'],
       ['11-10-2017', '4545', '100', '149', '6', '0', '66'],
       ['12-10-2017', '4340', '100', '140', '6', '0', '66'],
       ['13-10-2017', '1230', '100', '38', '7', '0', '66'],
       ['14-10-2017', '61', '100', '1', '5', '0', '66'],
       ['15-10-2017', '1258', '100', '40', '6', '0', '65'],
       ['16-10-2017', '3148', '100', '101', '8', '0', '65'],
       ['17-10-2017', '4687', '100', '152', '5', '0', '65'],
       ['18-10-2017', '4732', '300', '150', '6', '500', '65'],
       ['19-10-2017', '3519', '100', '113', '7', '0', '65'],
       ['20-10-2017', '1580', '100', '49', '5', '0', '65'],
       ['21-10-2017', '2822', '100', '86', '6', '0', '65'],
       ['22-10-2017', '181', '10

In [ ]:
data.shape

(96, 7)

In [ ]:
data[0]

array(['06-10-2017', '5464', '200', '181', '5', '0', '66'], dtype='<U10')

In [ ]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [ ]:
# date,step_count,mood,calories_burned,
# hours_of_sleep,bool_of_active,weight_kg

In [ ]:
data1=np.array([[1,2,3]])
print(data1)

[[1 2 3]]


In [ ]:
data1.T

array([[1],
       [2],
       [3]])

In [ ]:
data1.shape

(3, 1)

In [ ]:
a,b,c=data1.T

In [ ]:
a

array([1])

In [ ]:
b

array([2])

In [ ]:
c

array([3])

In [ ]:
date,step_count,mood,calories_burned,hours_of_sleep,bool_of_active,weight_kg=data.T

In [ ]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [ ]:
date=data[:,0]
step_count=data[:,1]
mood=data[:,2]

In [ ]:
step_count.dtype

dtype('<U10')

In [ ]:
step_count=np.array(step_count,dtype="int")
step_count.dtype

dtype('int64')

In [ ]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [ ]:
np.mean(step_count)

2935.9375

In [ ]:
calories_burned=np.array(calories_burned,dtype="int")
calories_burned[:5]

array([181, 197,   0, 174, 223])

In [ ]:
hours_of_sleep=np.array(hours_of_sleep,dtype="int")
hours_of_sleep[:5]

array([5, 8, 5, 4, 5])

In [ ]:
weight_kg=np.array(weight_kg,dtype="int")
weight_kg[:5]

array([66, 66, 66, 66, 66])

In [ ]:
mood

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', '300', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', '300', '200', '300', '300',
       '300', '300', '300', '300', '300', '200', '300', '300', '300',
       '300', '300', '300', '300', '300', '300', '300', '200', '300',
       '300', '300', '300', '300', '300', '300', '300', '300', '200',
       '100', '300', '300', '300', '300', '300', '300', '300', '100',
       '200', '200', '100', '100', '200', '200', '300', '200', '200',
       '100', '200', '100', '200', '200', '100', '100', '100', '100',
       '300', '200', '300', '200', '100', '100', '100', '200', '200',
       '100', '100', '300', '200', '200', '300'], dtype='<U10')

In [ ]:
mood[mood=='100']="sad"
mood

array(['200', 'sad', 'sad', 'sad', '200', 'sad', 'sad', 'sad', 'sad',
       'sad', 'sad', 'sad', '300', 'sad', 'sad', 'sad', 'sad', '200',
       '200', '200', '200', '200', '200', '300', '200', '300', '300',
       '300', '300', '300', '300', '300', '200', '300', '300', '300',
       '300', '300', '300', '300', '300', '300', '300', '200', '300',
       '300', '300', '300', '300', '300', '300', '300', '300', '200',
       'sad', '300', '300', '300', '300', '300', '300', '300', 'sad',
       '200', '200', 'sad', 'sad', '200', '200', '300', '200', '200',
       'sad', '200', 'sad', '200', '200', 'sad', 'sad', 'sad', 'sad',
       '300', '200', '300', '200', 'sad', 'sad', 'sad', '200', '200',
       'sad', 'sad', '300', '200', '200', '300'], dtype='<U10')

In [ ]:
mood[mood=='200']="neutral"
mood[mood=='300']="happy"

In [ ]:
mood

array(['neutral', 'sad', 'sad', 'sad', 'neutral', 'sad', 'sad', 'sad',
       'sad', 'sad', 'sad', 'sad', 'happy', 'sad', 'sad', 'sad', 'sad',
       'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'neutral',
       'happy', 'neutral', 'happy', 'happy', 'happy', 'happy', 'happy',
       'happy', 'happy', 'neutral', 'happy', 'happy', 'happy', 'happy',
       'happy', 'happy', 'happy', 'happy', 'happy', 'happy', 'neutral',
       'happy', 'happy', 'happy', 'happy', 'happy', 'happy', 'happy',
       'happy', 'happy', 'neutral', 'sad', 'happy', 'happy', 'happy',
       'happy', 'happy', 'happy', 'happy', 'sad', 'neutral', 'neutral',
       'sad', 'sad', 'neutral', 'neutral', 'happy', 'neutral', 'neutral',
       'sad', 'neutral', 'sad', 'neutral', 'neutral', 'sad', 'sad', 'sad',
       'sad', 'happy', 'neutral', 'happy', 'neutral', 'sad', 'sad', 'sad',
       'neutral', 'neutral', 'sad', 'sad', 'happy', 'neutral', 'neutral',
       'happy'], dtype='<U10')

In [ ]:
bool_of_active[bool_of_active=="0"]="inactive"
bool_of_active[bool_of_active=="500"]="active"

In [ ]:
bool_of_active

array(['inactive', 'inactive', 'inactive', 'inactive', 'active',
       'inactive', 'inactive', 'inactive', 'inactive', 'inactive',
       'inactive', 'inactive', 'active', 'inactive', 'inactive',
       'inactive', 'inactive', 'inactive', 'inactive', 'inactive',
       'inactive', 'inactive', 'inactive', 'inactive', 'inactive',
       'active', 'inactive', 'inactive', 'inactive', 'inactive', 'active',
       'inactive', 'inactive', 'inactive', 'inactive', 'inactive',
       'active', 'active', 'active', 'active', 'active', 'active',
       'active', 'active', 'active', 'inactive', 'inactive', 'inactive',
       'inactive', 'inactive', 'inactive', 'active', 'active', 'active',
       'active', 'active', 'active', 'active', 'active', 'active',
       'active', 'active', 'active', 'inactive', 'active', 'active',
       'inactive', 'active', 'active', 'active', 'active', 'active',
       'inactive', 'active', 'active', 'active', 'active', 'inactive',
       'inactive', 'inactive', 'inacti

In [ ]:
np.unique(mood)

array(['happy', 'neutral', 'sad'], dtype='<U10')

In [ ]:
np.unique(mood,return_counts=True)

(array(['happy', 'neutral', 'sad'], dtype='<U10'), array([40, 27, 29]))

In [ ]:
np.unique?

In [ ]:
np.mean(step_count)

2935.9375

In [ ]:
np.max(step_count)

7422

In [ ]:
np.argmax(step_count)

69

In [ ]:
date[np.argmax(step_count)]

'14-12-2017'

In [ ]:
calories_burned[np.argmax(step_count)]

243

In [ ]:
np.unique(mood[step_count>4000],return_counts=True)

(array(['happy', 'neutral', 'sad'], dtype='<U10'), array([22,  9,  7]))

In [ ]:
np.mean(hours_of_sleep)

5.21875

In [ ]:
z=np.unique(mood[step_count>4000],return_counts=True)

In [ ]:
z[0][0]

'happy'

In [ ]:
z[1]

array([22,  9,  7])

In [ ]:
np.unique(mood[hours_of_sleep<4],return_counts=True)

(array(['happy', 'neutral', 'sad'], dtype='<U10'), array([1, 5, 6]))

In [ ]:
np.unique(bool_of_active[hours_of_sleep>5],return_counts=True)

(array(['active', 'inactive'], dtype='<U10'), array([16, 17]))

In [ ]:
weight_kg

array([66, 66, 66, 66, 66, 66, 66, 66, 66, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64])

In [ ]:
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0 ])
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [ ]:
arr[arr>0]=1
arr[arr<0]=-1

In [ ]:
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [ ]:
arr1=np.where(arr>0,"1","-1")

In [ ]:
np.where?

In [ ]:
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [ ]:
arr1

array(['-1', '1', '1', '1', '-1', '-1', '-1', '-1', '1', '-1'],
      dtype='<U2')

In [ ]:
# 1.np.dot
# 2.np.matmul
# 3.@

In [ ]:
a=np.arange(1,10).reshape((3,3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b=np.arange(2,11).reshape((3,3))
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
np.matmul(a,b)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [ ]:
np.matmul(b,a)

array([[ 42,  51,  60],
       [ 78,  96, 114],
       [114, 141, 168]])

In [ ]:
a@b

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [ ]:
b@a

array([[ 42,  51,  60],
       [ 78,  96, 114],
       [114, 141, 168]])

In [ ]:
np.dot(a,b)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [ ]:
np.dot(b,a)

array([[ 42,  51,  60],
       [ 78,  96, 114],
       [114, 141, 168]])

In [ ]:
np.dot(4,5)

20

In [ ]:
np.matmul(4,5)

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
d=np.arange(1,5)
e=np.arange(2,6)
print(d)
print(e)

[1 2 3 4]
[2 3 4 5]


In [ ]:
np.dot(d,e)

40

In [ ]:
np.matmul(d,e)

40

In [ ]:
d*e

array([ 2,  6, 12, 20])

In [ ]:
d@e

40

In [ ]:
g=np.arange(1,13).reshape((3,4))
g

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
h=np.arange(1,13).reshape((4,3))

In [ ]:
h

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.dot(g,h)

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [ ]:
np.dot(h,g)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200],
       [173, 206, 239, 272]])

In [ ]:
j=np.arange(1,4).reshape((1,3))
j

array([[1, 2, 3]])

In [ ]:
h=np.arange(1,16).reshape((3,5))
h

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
np.dot(j,h)

array([[46, 52, 58, 64, 70]])

In [ ]:
np.dot(h,j)

ValueError: shapes (3,5) and (1,3) not aligned: 5 (dim 1) != 1 (dim 0)

In [ ]:
h=np.arange(1,16).reshape((5,3))
h

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
h

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
j.shape

(1, 3)

In [ ]:
np.dot(j,h.T)

array([[14, 32, 50, 68, 86]])

In [ ]:
# np.tile()

In [ ]:
t=np.arange(1,13).reshape((3,4))
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.tile(t,(2,2))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [ ]:
np.tile(t,(3,2))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [ ]:
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])

b = np.sort(a)

In [ ]:
b

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

In [ ]:
How can you create a 2D NumPy array mentioned below?
[[5.,5.,5.],
[5.,5.,5.],
[5.,5.,5.]]


In [ ]:

a= np.identity(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a= np.full((3,3),5.0)
print(a)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [ ]:

a= np.ones((3,3))
print(a)
a=a+5
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [ ]:

a=np.zeros((3,3))
a=a*5

In [ ]:
a=np.arange(1,10).reshape((3,3))

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.max(a, axis=0))

[7 8 9]


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])
a[2:] = b[::-1]
a

array([1, 2, 6, 7, 8])

In [ ]:
# [1,2,6,7,8]

In [ ]:
# [1,2,8,7,6]

In [ ]:
# [1,2,3,4,5,8,7,6]

In [ ]:
a = np.array([0,2,3])
b = np.array([1,3,5])

In [ ]:
a >= b

array([False, False, False])

![dog.jpeg](attachment:dog.jpeg)

In [ ]:
np.argsort([[23, 2, 54]], axis = 0) 

In [ ]:
a=np.array([[2,87,1,0,99]])
np.sort(a,axis=0)

array([[ 2, 87,  1,  0, 99]])

In [ ]:
np.argsort(a,axis=0)

array([[0, 0, 0, 0, 0]])

In [ ]:
np.sort(a,axis=1)

array([[ 0,  1,  2, 87, 99]])

In [ ]:
np.argsort(a,axis=1)

array([[3, 2, 0, 1, 4]])