In [1]:
print("Welcome to Numpy-1")
import numpy as np, math, os, pathlib, types, textwrap, random
print('NumPy version:', np.__version__)

Welcome to Numpy-1
NumPy version: 2.2.4


In [2]:
a=[1,2,3,4,5]
b = [i**2 for i in a]
print(b)

[1, 4, 9, 16, 25]


In [3]:
a=np.array([1,2,3,4,5])
a**2

array([ 1,  4,  9, 16, 25])

In [3]:
import numpy as np

In [4]:
b= np.array([1,2,3,4,5])
print(b)

[1 2 3 4 5]


In [5]:
type(b)

numpy.ndarray

In [6]:
b.dtype

dtype('int64')

In [7]:
a=range(10000)


In [8]:
%timeit [i**2 for i in a]


649 μs ± 10.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [19]:
b=np.arange(10000)

In [20]:
%timeit b**2

3.46 µs ± 69.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
a=range(1,10,5)

In [10]:
for i in a:
    print(i)

1
6


In [11]:
b=np.arange(1,10,0.5)
print(b)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [38]:
a=np.array([1,2,3,4,5])
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [40]:
a=np.array([1,2,3,4,5,4.5])
print(a)
print(type(a))
print(a.dtype)

[1.  2.  3.  4.  5.  4.5]
<class 'numpy.ndarray'>
float64


In [41]:
a=np.array([1,2,3,4,5,"a"])
print(a)
print(type(a))
print(a.dtype)

['1' '2' '3' '4' '5' 'a']
<class 'numpy.ndarray'>
<U21


In [42]:
a=np.array([1,2,3,4,5,"a",4.4])
print(a)
print(type(a))
print(a.dtype)

['1' '2' '3' '4' '5' 'a' '4.4']
<class 'numpy.ndarray'>
<U32


In [44]:
a=np.array([True,False])
print(a)
print(type(a))
print(a.dtype)

[ True False]
<class 'numpy.ndarray'>
bool


In [45]:
a=np.array([1,True,False])
print(a)
print(type(a))
print(a.dtype)

[1 1 0]
<class 'numpy.ndarray'>
int64


In [46]:
a=np.array([1,2,3,4,5])
a.ndim


1

In [47]:
a.shape

(5,)

In [ ]:
# a=np.arange(start,stop,step)

In [ ]:
np.linspace(start,end,num)

In [50]:
a=np.linspace(1,10,10)
print(a)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [52]:
a=np.linspace(1,10,19)
print(a)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [54]:
a=np.linspace(1,20,20)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


In [55]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
a.ndim

2

In [57]:
a.shape

(3, 3)

In [58]:
type(a)

numpy.ndarray

In [66]:
b= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [67]:
a=np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [69]:
a.reshape((1,12))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [70]:
a.reshape((12,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [71]:
a.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [72]:
a.reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [73]:
a.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
a.reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [81]:
a.reshape((-1,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [77]:
a.reshape((6,-1))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [78]:
a.reshape((-1,-1))

ValueError: can only specify one unknown dimension

In [79]:
a.reshape((10,2))

ValueError: cannot reshape array of size 12 into shape (10,2)

In [82]:
a.reshape((-1,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [83]:
a.reshape((1,-1))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [85]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [87]:
b=np.arange(1,17)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [93]:
c=b.reshape((1,16))
print(c)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]


In [94]:
c.shape

(1, 16)

In [95]:
c=b.reshape((16,1))
print(c)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]]


In [96]:
c.shape

(16, 1)

In [97]:
b=np.arange(1,13)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [98]:
c=b.reshape((3,4))
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [99]:
c.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [100]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
c


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
c.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [103]:
b=n.rp.arange(1,13).reshape((3,4))
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [104]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
a=np.arange(1,13)

In [106]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [107]:
a[0:5]

array([1, 2, 3, 4, 5])

In [108]:
a[5:11]

array([ 6,  7,  8,  9, 10, 11])

In [109]:
a[-1]

12

In [110]:
a[4]

5

In [111]:
a[-4:]

array([ 9, 10, 11, 12])

In [113]:
a[::3]

array([ 1,  4,  7, 10])

In [114]:
a[::-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [115]:
a[::-2]

array([12, 10,  8,  6,  4,  2])

In [116]:
a[-2:-10:-1]

array([11, 10,  9,  8,  7,  6,  5,  4])

In [117]:
a[-10:-2:-1]

array([], dtype=int64)

In [118]:
a[12::1]

array([], dtype=int64)

In [119]:
a=np.arange(1,13).reshape((4,3))

In [120]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# a[row][column] #method1
# a[row,column] #method2

In [121]:
a[0]

array([1, 2, 3])

In [122]:
a[0,:]

array([1, 2, 3])

In [123]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
a[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
a[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [127]:
a[1:3,:2]

array([[4, 5],
       [7, 8]])

In [131]:
a[1:3,1:2]

array([[5],
       [8]])

In [132]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [133]:
a[::2,::2]

array([[1, 3],
       [7, 9]])

In [134]:
a[1::2,::2]

array([[ 4,  6],
       [10, 12]])

In [141]:
a[[0,1,3],:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [140]:
a[(0,1,3),:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [142]:
a[(0,1,3),1:]

array([[ 2,  3],
       [ 5,  6],
       [11, 12]])

In [144]:
a=np.arange(1,13).reshape((2,2))
print(a)

ValueError: cannot reshape array of size 12 into shape (2,2)

In [145]:
a=np.arange(1,13).reshape((6,2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [146]:
a=np.arange(1,13).reshape((6,10))
print(a)

ValueError: cannot reshape array of size 12 into shape (6,10)

In [148]:
a=np.arange(1,13)

In [149]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [150]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [152]:
a.reshape((-1,1)).shape

(12, 1)